# One CLI to format the code tree - https://github.com/numtide/treefmt

# Do not exit with error if a configured formatter is missing
# Env $TREEFMT_ALLOW_MISSING_FORMATTER
allow-missing-formatter = false

# Exclude files or directories matching the specified globs
# Env $TREEFMT_EXCLUDES
excludes = [".gitignore", "*.el", "*.gif", "*.lock", "*.otf", ".keep"]

# Exit with error if any changes were made during execution
# Useful for CI
# Env $TREEFMT_FAIL_ON_CHANGE
fail-on-change = false

# Log paths that did not match any formatters at the specified log level
# Possible values are <debug|info|warn|error|fatal>
# Env $TREEFMT_ON_UNMATCHED
on-unmatched = "info"

# The root directory from which treefmt will start walking the filesystem
# Defaults to the directory containing the config file
# Env $TREEFMT_TREE_ROOT
# tree-root = "/tmp/foo"

# File to search for to find the tree root (if tree-root is not set)
# Env $TREEFMT_TREE_ROOT_FILE
tree-root-file = ".git/config"

# Set the verbosity of logs
# 0 = warn, 1 = info, 2 = debug
# Env $TREEFMT_VERBOSE
verbose = 1

# The method used to traverse the files within the tree root
# Currently, we support 'auto', 'git' or 'filesystem'
# Env $TREEFMT_WALK
walk = "git"

# n.b. `nixfmt-rfc-style`
[formatter.nixfmt]
command = "alejandra"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
options = ["format", "--write", "--no-errors-on-unmatched"]
excludes = []
includes = [
  "*.js",
  "*.ts",
  "*.mjs",
  "*.mts",
  "*.cjs",
  "*.cts",
  "*.jsx",
  "*.tsx",
  "*.d.ts",
  "*.d.cts",
  "*.d.mts",
  "*.json",
  "*.jsonc",
]


[formatter.clang-format]
command = "clang-format"
excludes = []
options = ["-i"]
includes = [
  "*.c",
  "*.cc",
  "*.cpp",
  "*.h",
  "*.hh",
  "*.hpp",
  "*.glsl",
  "*.vert",
  ".tesc",
  ".tese",
  ".geom",
  ".frag",
  ".comp",
]

[formatter.hclfmt]
command = "hclfmt"
options = ["-w"]
excludes = []
includes = ["*.hcl"]

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.rubocop]
command = "rubocop"
options = []
excludes = []
includes = ["*.rb"]

[formatter.ruff-check]
command = "ruff"
options = ["check", "--fix"]
excludes = []
includes = ["*.py", "*.pyi"]

[formatter.ruff-format]
command = "ruff"
options = ["format"]
excludes = []
includes = ["*.py", "*.pyi"]

[formatter.shellcheck]
command = "shellcheck"
options = []
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]

[formatter.shfmt]
command = "shfmt"
options = ["-s", "-w", "-i", "2"]
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]

[formatter.terraform]
command = "terraform"
options = ["fmt"]
excludes = []
includes = ["*.tf", "*.tfvars", "*.tftest.hcl"]

[formatter.taplo]
command = "taplo"
options = ["format"]
excludes = []
includes = ["*.toml"]

[formatter.yamlfmt]
command = "yamlfmt"
options = []
excludes = []
includes = ["*.yaml", "*.yml"]

[formatter.zig]
command = "zig"
excludes = []
includes = ["*.zig", "*.zon"]
options = ["fmt"]
