# generated by cabal2nix — do not edit; re-run `cabal2nix .` to update.
{
  mkDerivation,
  base,
  containers,
  dhall,
  lib,
  optparse-applicative,
  text,
}:
mkDerivation {
  pname = "coredns-zone";
  version = "0.1.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base
    containers
    dhall
    optparse-applicative
    text
  ];
  description = "Render the typed Dhall topology registry to a CoreDNS zone";
  license = lib.meta.getLicenseFromSpdxId "BSD-3-Clause";
  mainProgram = "coredns-zone";
}
