# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#                                    // new-suzuki // themes module
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#
# Installs the preset JSON files and theme-switch script.
#
{
  pkgs,
  config,
  lib,
  ...
}:
let
  inherit (lib) mkIf;

  cfg = config.hyper-modern-nixos.new-suzuki;

  presets = import ./presets.nix;

  themeJson =
    name: preset:
    pkgs.writeText "new-suzuki-theme-${name}.json" (
      builtins.toJSON (
        preset.tokens
        // {
          inherit (preset)
            label
            family
            polarity
            luminance
            ;
          aesthetic = preset.aesthetic;
          "font-name" = config.stylix.fonts.monospace.name;
        }
      )
    );

  themeSwitch = pkgs.writeShellScriptBin "theme-switch" ''
            set -euo pipefail
            DIR="${config.xdg.configHome}/quickshell/themes"
            DEST="${config.xdg.configHome}/quickshell/palette.json"
            STATE="${config.xdg.configHome}/quickshell/.current-theme"

            if [ $# -eq 0 ]; then
              echo "available presets:"
              ls "$DIR"/*.json 2>/dev/null | xargs -I{} basename {} .json | sed 's/^/  /'
              echo "current: $(cat "$STATE" 2>/dev/null || echo 'unknown')"
              exit 0
            fi

            THEME="$1"
            SRC="$DIR/$THEME.json"

            if [ ! -f "$SRC" ]; then
              echo "preset '$THEME' not found. available:"
              ls "$DIR"/*.json 2>/dev/null | xargs -I{} basename {} .json | sed 's/^/  /'
              exit 1
            fi

            # Remove the nix-store symlink if present and write a real file
            # so the FileView watcher picks up the change
            rm -f "$DEST"
            cp "$SRC" "$DEST"
            chmod 644 "$DEST"
            echo "$THEME" > "$STATE"

            # ── Ripple to other apps ──────────────────────────────────────────────
            # Quickshell picks up palette.json via FileView (instant).
            # Other apps need their own theme files written.

            # Parse palette values from the JSON
            SURFACE=$(python3 -c "import json;d=json.load(open('$DEST'));print(d.get('surface','#191c20'))" 2>/dev/null || echo "#191c20")
            INK=$(python3 -c "import json;d=json.load(open('$DEST'));print(d.get('ink','#d8e0e7'))" 2>/dev/null || echo "#d8e0e7")
            ACCENT=$(python3 -c "import json;d=json.load(open('$DEST'));print(d.get('accent','#54aeff'))" 2>/dev/null || echo "#54aeff")
            BORDER=$(python3 -c "import json;d=json.load(open('$DEST'));print(d.get('border','#2a3039'))" 2>/dev/null || echo "#2a3039")
            PAPER=$(python3 -c "import json;d=json.load(open('$DEST'));print(d.get('paper','#1f232a'))" 2>/dev/null || echo "#1f232a")
            ERROR=$(python3 -c "import json;d=json.load(open('$DEST'));print(d.get('error','#f85149'))" 2>/dev/null || echo "#f85149")
            SUCCESS=$(python3 -c "import json;d=json.load(open('$DEST'));print(d.get('success','#218bff'))" 2>/dev/null || echo "#218bff")

            # Detect light/dark
            LUM=$(python3 -c "
        import json
        d=json.load(open('$DEST'))
        s=d.get('surface','#191c20')[1:]
        r,g,b=int(s[0:2],16),int(s[2:4],16),int(s[4:6],16)
        print('light' if (0.299*r+0.587*g+0.114*b)/255>0.5 else 'dark')
        " 2>/dev/null || echo "dark")

            # ── GTK colors.css ────────────────────────────────────────────────────
            GTKDIR3="${config.xdg.configHome}/gtk-3.0"
            GTKDIR4="${config.xdg.configHome}/gtk-4.0"
            mkdir -p "$GTKDIR3" "$GTKDIR4"
            GTK_COLORS="/* auto-generated by theme-switch */
        @define-color accent_bg_color $ACCENT;
        @define-color accent_color $ACCENT;
        @define-color accent_fg_color $SURFACE;
        @define-color window_bg_color $SURFACE;
        @define-color window_fg_color $INK;
        @define-color view_bg_color $SURFACE;
        @define-color view_fg_color $INK;
        @define-color headerbar_bg_color $PAPER;
        @define-color headerbar_fg_color $INK;
        @define-color card_bg_color $PAPER;
        @define-color card_fg_color $INK;
        @define-color popover_bg_color $PAPER;
        @define-color popover_fg_color $INK;
        @define-color dialog_bg_color $PAPER;
        @define-color dialog_fg_color $INK;
        @define-color sidebar_bg_color $PAPER;
        @define-color sidebar_fg_color $INK;
        @define-color destructive_bg_color $ERROR;
        @define-color destructive_fg_color $SURFACE;
        @define-color error_bg_color $ERROR;
        @define-color error_fg_color $SURFACE;
        @define-color success_bg_color $SUCCESS;
        @define-color success_fg_color $SURFACE;
        @define-color warning_bg_color $ACCENT;
        @define-color warning_fg_color $SURFACE;
        @define-color borders $BORDER;
        @define-color unfocused_borders $BORDER;
        "
            echo "$GTK_COLORS" > "$GTKDIR3/colors.css"
            cp "$GTKDIR3/colors.css" "$GTKDIR4/colors.css"

            # GTK color-scheme (dark/light preference)
            if [ "$LUM" = "dark" ]; then
              gsettings set org.gnome.desktop.interface color-scheme prefer-dark 2>/dev/null || true
            else
              gsettings set org.gnome.desktop.interface color-scheme prefer-light 2>/dev/null || true
            fi

        # ── Hyprland borders ──────────────────────────────────────────────────
        # Strip the # from hex colors for Hyprland's rgba() format
        ACCENT_HEX=$(echo "$ACCENT" | sed 's/#//')
        BORDER_HEX=$(echo "$BORDER" | sed 's/#//')
        HYPR_SIG=$(ls /run/user/$(id -u)/hypr/ 2>/dev/null | tail -1)
        if [ -n "$HYPR_SIG" ]; then
          export HYPRLAND_INSTANCE_SIGNATURE="$HYPR_SIG"
          hyprctl keyword general:col.active_border "rgba(''\${ACCENT_HEX}ff) rgba(''\${ACCENT_HEX}ff) 0deg" 2>/dev/null || true
          hyprctl keyword general:col.inactive_border "rgba(''\${BORDER_HEX}66)" 2>/dev/null || true
        fi

        # ── Qt color scheme ───────────────────────────────────────────────────
        # Write a .colors file that qt5ct/qt6ct can read
        QTDIR="${config.xdg.dataHome}/color-schemes"
        mkdir -p "$QTDIR"
        ACCENT_RGB=$(python3 -c "h='$ACCENT';r,g,b=int(h[1:3],16),int(h[3:5],16),int(h[5:7],16);print(f'{r},{g},{b}')")
        INK_RGB=$(python3 -c "h='$INK';r,g,b=int(h[1:3],16),int(h[3:5],16),int(h[5:7],16);print(f'{r},{g},{b}')")
        SURFACE_RGB=$(python3 -c "h='$SURFACE';r,g,b=int(h[1:3],16),int(h[3:5],16),int(h[5:7],16);print(f'{r},{g},{b}')")
        PAPER_RGB=$(python3 -c "h='$PAPER';r,g,b=int(h[1:3],16),int(h[3:5],16),int(h[5:7],16);print(f'{r},{g},{b}')")
        BORDER_RGB=$(python3 -c "h='$BORDER';r,g,b=int(h[1:3],16),int(h[3:5],16),int(h[5:7],16);print(f'{r},{g},{b}')")
        QT_COLORS="[General]
    ColorScheme=NewSuzuki
    Name=NewSuzuki

    [Colors:Button]
    BackgroundNormal=$PAPER_RGB
    DecorationFocus=$ACCENT_RGB
    ForegroundNormal=$INK_RGB

    [Colors:Selection]
    BackgroundNormal=$ACCENT_RGB
    ForegroundNormal=$SURFACE_RGB

    [Colors:View]
    BackgroundAlternate=$PAPER_RGB
    BackgroundNormal=$SURFACE_RGB
    DecorationFocus=$ACCENT_RGB
    ForegroundNormal=$INK_RGB

    [Colors:Window]
    BackgroundNormal=$SURFACE_RGB
    ForegroundNormal=$INK_RGB

    [WM]
    activeBackground=$PAPER_RGB
    activeForeground=$INK_RGB
    "
        echo "$QT_COLORS" > "$QTDIR/NewSuzuki.colors"

        # ── Ghostty terminal ──────────────────────────────────────────────────
        # Ghostty hot-reloads its config on file change.
        GHOSTTY_CONF="${config.xdg.configHome}/ghostty/themes/new-suzuki"
        mkdir -p "$(dirname "$GHOSTTY_CONF")"
        echo "background = $SURFACE" > "$GHOSTTY_CONF"
        echo "foreground = $INK" >> "$GHOSTTY_CONF"
        echo "cursor-color = $ACCENT" >> "$GHOSTTY_CONF"
        echo "selection-background = $PAPER" >> "$GHOSTTY_CONF"
        echo "selection-foreground = $INK" >> "$GHOSTTY_CONF"
        echo "palette = 0=$BORDER" >> "$GHOSTTY_CONF"
        echo "palette = 4=$ACCENT" >> "$GHOSTTY_CONF"
        echo "palette = 9=$ERROR" >> "$GHOSTTY_CONF"
        echo "palette = 10=$SUCCESS" >> "$GHOSTTY_CONF"

        # ── Emacs ─────────────────────────────────────────────────────────────
        # Load the preset's Emacs theme if one exists for it
        if command -v emacsclient &>/dev/null; then
          emacsclient -e "(when (fboundp 'load-theme) (load-theme 'base16-onosendai t))" 2>/dev/null || true
        fi

        # ── Neovim ────────────────────────────────────────────────────────────
        # Send colorscheme command to running nvim instances via their sockets
        for sock in /run/user/$(id -u)/nvim.*.0; do
          [ -S "$sock" ] && nvim --server "$sock" --remote-send '<Cmd>colorscheme base16-onosendai<CR>' 2>/dev/null &
        done
        wait 2>/dev/null || true

        echo "switched to $THEME (quickshell + GTK + Hyprland + Qt + terminals + editors)"
  '';
in
{
  config = mkIf cfg.enable {
    home.packages = [ themeSwitch ];

    xdg.configFile."quickshell/themes" = {
      source = pkgs.linkFarm "new-suzuki-themes" (
        pkgs.lib.mapAttrsToList (name: preset: {
          name = "${name}.json";
          path = themeJson name preset;
        }) presets
      );
    };
  };
}
